spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/rwclient?serverTimezone=UTC
    username: root
    password: 1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: ${PORT:80}
  servlet:
    session:
      timeout: 10m
telega:
  name: ${telega_name}
  apiToken: ${telega_apiToken}
rw:
  proxy: ${rw_proxy}
logging:
  level:
    root: info
    org.springframework.web: info
    org.hibernate: info
    io.bot: debug
---
spring:
  profiles: dev

---
spring:
  profiles: prod
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
     hibernate:
      jdbc:
       lob:
        non_contextual_creation: true
