spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/rwclient?serverTimezone=UTC
    username: root
    password: 1
server:
  port: 80
  servlet:
    session:
      timeout: 100m