spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: ${datasource.url}
    username: ${datasource.username}
    password: ${datasource.password}
server:
  port: 80
  servlet:
    session:
      timeout: 100m